<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['user_profile_app_description'] = 'Приложение "Профиль пользователя" используется для изменения пароля в зависимости от настроек системы и обновлении других настроек профиля.';
$lang['user_profile_app_name'] = 'Профиль пользователя';
$lang['user_profile_contact_information'] = 'Контактная информация';
