<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['user_profile_app_description'] = 'Aplikacja profilu użytkownika używana jest do zmiany hasła i w zależności od ustawień systemowy, także do aktualizacji innych ustawień profilu.';
$lang['user_profile_app_name'] = 'Profil użytkownika';
$lang['user_profile_contact_information'] = 'Informacje kontaktowe';
